name: Sync workouts from Dropbox

permissions:
  contents: write

on:
  schedule:
    - cron: "*/15 * * * *" # каждые 15 минут
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download CSV from Dropbox
        run: |
          curl -L "https://www.dropbox.com/scl/fi/u2khdh4pk8mv24xslz79u/Workouts-2026.csv?rlkey=1hm6gcs896e1hdf8458bfpctq&st=ud1lv8nw&dl=1" \
          -o Workouts-2026.csv

      - name: Commit if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add Workouts-2026.csv
          git diff --cached --quiet || git commit -m "auto: sync workouts"
          git push
